name: praxis_internals
description: Praxis Dashboard (production env)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.0
  logger: ^1.3.0

  amplify_auth_cognito: ^1.0.0-0
  amplify_authenticator: ^1.0.0-0
  amplify_flutter: ^1.0.0-0
  fl_chart: ^0.62.0
  csv: ^5.0.2

dependency_overrides:
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
